name: JS Demo

on: 
  workflow_dispatch:
    inputs:
      user-name:
        description: 'Name to great'
        type: variable 
        required: false

jobs:
  js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Greeting Action
        uses: gustav-lindstedt/js-action
        id: hello
        with:
          user-name: 'Gustav'
    
      - name: Get Output
        run: |
          echo "Greeting: ${{ steps.hello.outputs.greeting }}"
          echo "Time: ${{ steps.hello.outputs.time }}"
    